config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
   root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_comment_counter

  def update_comment_counter
    post.update(CommentCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_likes_counter

  def update_likes_counter
    post.update(LikesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :CommentCounter, :LikesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_post_counter

  def update_post_counter
    author.update(PostCounter: author.posts.all.count)
  end

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  # def comments
  #   comments.order(created_at: :desc)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', class_name: 'Post'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :Name, presence: true, length: { maximum: 250 }

  validates :PostCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email Name Photo])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:Name, :email, :Photo, :Bio, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.new(comments_params)
    comment.author = current_user
    comment.post_id = params[:post_id]
    if comment.save
      redirect_to user_post_path(current_user.id, comment.post_id), notice: 'comment added'
    else
      render :new, alert: 'Failed to post comment, Please try again later'
    end
  end

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: current_user.id, post_id: params[:post_id])
    redirect_to user_post_path(current_user, @post) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)

    # @comments = Comment.where(post_id: @posts, author_id: @user)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.author_id = current_user.id
    if @post.save
      flash[:notice] = 'Post successfully created!'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Error: Error occurred when creating post'
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:id], author_id: params[:user_id])
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(params[author_id: @user.id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add new comments</h1>

<%= form_with model: @comment, url: user_post_comments_url, method: :post, local: true, scope: :comment do |form| %>
  <div >
    <%= form.label :text %><br>
    <%= form.text_area :text%>
  </div>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_user.html.erb
<div class='center'>
    <div>
        <%= "Total number of users: #{@users.length}" %>
    </div>
    <% @users.each do |user| %>
        <div class='userDiv'>
            <div>
                <%= image_tag user.Photo %>
            </div>
            <div class='border flex'>
                <%= link_to user.Name, user %>
                <div class='bottom_flex'>
                    <%= "Number of posts: #{user.PostCounter}" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class='center'>
    <div class='flex '>
        <div> <%= image_tag @user.Photo %> </div>
        <div class='border'>
            <%= @user.Name %>
            <div class='bottom_flex'>
                <%= @user.PostCounter %>
            </div>
        </div>
            </div>
                    <% @posts.each do |post| %>
 
                       <div class='borBtm'>
                       <div class='border'>
                            <div class='flex column'>
                                <%= "Post: #{post.id}" %>
                                <%=link_to post.title, user_post_path(@user.id, post.id)%>
                            </div>
                            <div>
                                <%= "Comments: #{post.CommentCounter}" %>
                            </div>
                            <div>
                                <%= " Likes: #{post.LikesCounter}" %>
                            </div>

                            <%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes" do |form| %>
                                <%= form.submit "Like Post" %>
                            <% end %>
                        </div>
                        <% if post.five_recent_comments.includes([:author]).count.zero? %>
                        <p class='border'> No comments on this post yet <p>
                        <% else %>
                        <div class='border'>
                            <% post.five_recent_comments.includes([:author]).each do |post| %>
                                <div>
                                <%= "#{post.author.Name}:" %>
                                    <%= post.text %>
                                </div>
                            <% end %>
                            <% end %>
                        </div>
                        <% %>
                        </div>
                    <% end %>
                </div>

    </div>
    <section>
    <button>Pagination</button>
    <button><%= link_to 'Create a new post', new_user_post_path(@user.id) %></button>
    </section>
</div>

app/views/posts/new.html.erb
<h1 >Add A New Post</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
  <div >
    <div >
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div >
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </div>
    <%= form.submit "Click to Add Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class='center2'>
    <div class='border'>
        <div class='flex jstSbt'>
            Post by <%= @post.author.Name %>
            <div>
                Comments : <%= @post.CommentCounter %>,
                Likes : <%= @post.LikesCounter %>
            </div>
        </div>

        <div>
            <%= @post.title %>
        </div>
    </div>

    <div class='border'>
    <% if @post.comments.count.zero? %>
    <p> Post has no comments yet </p>
    <% else %>
    <% @post.comments.each do |comment| %>
        <div>
            <%= comment.author.Name %>:
            <%= comment.text %> 
        </div>
        <div>
        </div>
    <% end %>
    <% end %>
</div>
<button> <%= link_to 'Write a comment', new_user_post_comment_path(post_id: @post.id) %></button>'
</div>

app/views/users/index.html.erb
<div >
 <%= render partial: 'partials/user' %>
</div>

app/views/users/show.html.erb
<div class='center'>
    <div class="flex">
        <div>
            <%= image_tag @user.Photo %>
        </div>
        <div class="border">
            <div>
                <%= @user.Name %>
            </div>
            <div class='bottom_flex'>
                <%= "Number of posts: #{@user.PostCounter} " %>
            </div>
        </div>
    </div>
    <div class='border'>
        <p>Bio</p>
        <%= @user.Bio %>
    </div>

    <div class='borBtm'>
        <% @user.three_posts.each do |post| %>
            <div class='border borBtm flex jstSbt'>
                <div>
                    <div>
                        <%= " Post: #{post.title }"%>
                    </div>
                    </br>
                    <div>
                        <%= " Text: #{post.text}" %>
                    </div>
                </div>
                <div>
                    <%= "Comments: #{post.CommentCounter}" %>
                    <%= "Likes: #{post.LikesCounter}" %>
                </div>
            </div>
        <% end %>
    </div>

    <button>
    <%= link_to "See all posts" , user_posts_path(@user.id) %>
</button>
</div>